apiVersion: v1

kind: ConfigMap

metadata:
  name: { { include "django-app.fullname" . } }

data:
  DJANGO_DEBUG: { { .Values.env.DJANGO_DEBUG | quote } }

  DJANGO_ALLOWED_HOSTS: { { .Values.env.DJANGO_ALLOWED_HOSTS | quote } }

  POSTGRES_DB: { { .Values.env.POSTGRES_DB | quote } }

  POSTGRES_PORT: { { .Values.env.POSTGRES_PORT | quote } }

  POSTGRES_HOST: { { .Values.env.POSTGRES_HOST | quote } }
