replicaCount: 2

image:
  repository: YOUR_AWS_ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/django-eks-project/django
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

containerPort: 8000

resources:
  requests:
    cpu: 250m
    memory: 256Mi

  limits:
    cpu: 500m
    memory: 512Mi

env:
  DJANGO_DEBUG: "False"

  DJANGO_ALLOWED_HOSTS: "*"

  POSTGRES_DB: "django_db"

  POSTGRES_PORT: "5432"

  POSTGRES_HOST: ""

hpa:
  enabled: true

  minReplicas: 2

  maxReplicas: 5

  targetCPUUtilizationPercentage: 70
