pipeline {

    agent any

    environment {
        AWS_REGION = 'eu-central-1'

        ECR_REPOSITORY = 'django-eks-project/django'

        IMAGE_TAG = "${BUILD_NUMBER}"

        AWS_ACCOUNT_ID = credentials('aws-account-id')

        ECR_REGISTRY = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"

        IMAGE_NAME = "${ECR_REGISTRY}/${ECR_REPOSITORY}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }


        stage('Build Docker Image') {
            steps {
                sh """
                    docker build \
                      -t ${IMAGE_NAME}:${IMAGE_TAG} \
                      .
                """
            }
        }


        stage('Login to ECR') {
            steps {
                sh """
                    aws ecr get-login-password \
                      --region ${AWS_REGION} \
                    | docker login \
                      --username AWS \
                      --password-stdin ${ECR_REGISTRY}
                """
            }
        }


        stage('Push Docker Image') {
            steps {
                sh """
                    docker push ${IMAGE_NAME}:${IMAGE_TAG}
                """
            }
        }


        stage('Push Latest') {
            steps {
                sh """
                    docker tag \
                      ${IMAGE_NAME}:${IMAGE_TAG} \
                      ${IMAGE_NAME}:latest

                    docker push \
                      ${IMAGE_NAME}:latest
                """
            }
        }
    }


    post {

        success {
            echo "Docker image successfully pushed to ECR"
            echo "Image: ${IMAGE_NAME}:${IMAGE_TAG}"
        }

        failure {
            echo "CI pipeline failed"
        }
    }
}